#!/usr/bin/env python3
"""
scripts/_gen_notebooks.py

Generates all production notebooks under:
  notebooks/runs/     — one per simulation case (vacuum, seeded H2/Kr, callback H2/Kr)
  notebooks/analysis/ — cross-cutting analysis notebooks

Run from project root:
    python scripts/_gen_notebooks.py
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT        = Path(__file__).resolve().parent.parent
NB_RUNS     = ROOT / "notebooks" / "runs"
NB_ANALYSIS = ROOT / "notebooks" / "analysis"
NB_RUNS.mkdir(parents=True, exist_ok=True)
# Ensure src/ is in sys.path
import sys
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

from plasma_column.notebook_utils import (
    make_code_cell as code,
    make_markdown_cell as md,
    create_notebook as notebook,
    write_notebook_file,
    COMMON_IMPORTS,
    PLOT_IMPORTS,
)


PHYS_CHECKS = [
    "## Physics checks (AGENTS.md)\n",
    "\n",
    "- [ ] Beam velocity consistent with 30 keV proton energy\n",
    "- [ ] Macroparticle weights are physically meaningful\n",
    "- [ ] Species ordering in ParticleNumber is correct\n",
    "- [ ] Ne and Ni increase for the correct physics reason\n",
    "- [ ] K_eff/K0 never negative unless labelled overcompensation\n",
    "- [ ] Beam envelope changes consistent with sign and magnitude of compensation\n",
    "- [ ] Gas pressure and interaction length acceptable\n",
]


def load_diag_cell(varname, case_dir_expr):
    return code([
        "import warnings\n",
        f"_OUT = {case_dir_expr}\n",
        "_diag_candidates = [\n",
        "    _OUT / 'reducedfiles' / 'ParticleNumber_red.txt',\n",
        "    _OUT / 'neutralization_from_particle_number.csv',\n",
        "]\n",
        "_diag = next((p for p in _diag_candidates if p.exists()), None)\n",
        "if _diag:\n",
        "    with warnings.catch_warnings():\n",
        "        warnings.simplefilter('ignore')\n",
        f"        {varname} = load_particle_number_diagnostic(_diag)\n",
        f"        {varname} = compute_particle_number_metrics({varname})\n",
        f"    print(f'Loaded {{len({varname})}} steps from {{_diag.name}}')\n",
        f"    display({varname}.tail())\n",
        "else:\n",
        "    print('No diagnostic file yet — run the simulation first.')\n",
        f"    {varname} = None\n",
    ])


def plot_diag_cell(varname, case_name):
    return code([
        f"if {varname} is not None:\n",
        f"    plot_neutralization_panel({varname}, PLOTS_DIR, case_name='{case_name}')\n",
        f"    plot_species_growth_rates({varname}, PLOTS_DIR,\n",
        f"                              case_name='{case_name}', smooth_window=7)\n",
        "    plot_bunched_beam_keff(\n",
        f"        {varname}['time'].values * 1e9,\n",
        f"        {varname}['eta_net'].values.clip(0, 1), PLOTS_DIR,\n",
        f"        case_name='{case_name}',\n",
        "        bunching_factors=[1.0, 2.0, 3.0, 5.0],\n",
        "    )\n",
        "    plt.show()\n",
        f"    print('Final eta_net   =', {varname}['eta_net'].iloc[-1])\n",
        f"    print('Final K_eff/K0  =', {varname}['keff_over_k0'].iloc[-1])\n",
    ])


def summary_cell(varname, case_name, gas, pressure):
    return code([
        f"if {varname} is not None:\n",
        "    row = {\n",
        f"        'case':          '{case_name}',\n",
        f"        'gas':           '{gas}',\n",
        f"        'pressure':      '{pressure} Torr',\n",
        f"        'n_steps':       len({varname}),\n",
        f"        'final_eta_e':   {varname}['eta_electron_only'].iloc[-1],\n",
        f"        'final_eta_net': {varname}['eta_net'].iloc[-1],\n",
        f"        'final_keff_K0': {varname}['keff_over_k0'].iloc[-1],\n",
        "    }\n",
        "    display(pd.DataFrame([row]))\n",
    ])


# ── vacuum reference ──────────────────────────────────────────────────────────
def make_vacuum_nb():
    cells = [
        md(["# Vacuum Reference Run\n", "\n",
            "Baseline run **without** a plasma neutralizer.\n",
            "Establishes unneutralized beam propagation and verifies K_eff/K0 ≈ 1.\n",
            "\n",
            "**Beamline**: `buncher → [plasma neutralizer] → solenoid → Q1 → Q2 → spiral inflector`\n",
            "\n",
            "> Tip: set `MAX_STEPS = 500` and `DIAG_PERIOD = 100` for a smoke test first.\n"]),
        code(COMMON_IMPORTS),
        code([
            "from plasma_column.notebook_utils import print_simulation_config\n",
            "SCRIPT = _ROOT / 'plasma_column_mcc_picmi_v7.py'\n",
            "_DEFAULTS = {\n",
            "    'script':               'plasma_column_mcc_picmi_v7.py',\n",
            "    'case':                 'vacuum_reference',\n",
            "    'gas':                  'H2',\n",
            "    'neutralization':       0.0,\n",
            "    'mcc':                  'none',\n",
            "    'pressure_torr':        '1e-5',\n",
            "    'plasma_age [s]':       '2e-4',\n",
            "    'max_steps':            120000,\n",
            "    'diag_period':          5000,\n",
            "    'reduced_diag_period':  100,\n",
            "    'nx / ny / nz':         '32 / 32 / 256',\n",
            "}\n",
            "_OVERRIDES = {}  # e.g. {'max_steps': 500, 'diag_period': 100}\n",
            "print_simulation_config(\n",
            "    notebook_title='Vacuum Reference Run',\n",
            "    defaults=_DEFAULTS, overrides=_OVERRIDES,\n",
            "    extra_info={'output root': str(RUNS_DIR / 'vacuum_reference')},\n",
            ")\n",
        ]),
        md(["## 1. Configure\n"]),
        code([
            "MAX_STEPS      = 120000   # reduce to 500 for smoke test\n",
            "DIAG_PERIOD    = 5000\n",
            "REDUCED_PERIOD = 100\n",
            "NX, NY, NZ     = 32, 32, 256\n",
            "OUT_DIR = RUNS_DIR / 'vacuum_reference'\n",
            "OUT_DIR.mkdir(parents=True, exist_ok=True)\n",
            "cmd = [\n",
            "    sys.executable, str(SCRIPT), '--run',\n",
            "    '--output_dir',          str(OUT_DIR),\n",
            "    '--gas',                 'H2',\n",
            "    '--neutralization',      '0.0',\n",
            "    '--mcc',                 'none',\n",
            "    '--pressure_torr',       '1e-5',\n",
            "    '--plasma_age',          '2e-4',\n",
            "    '--max_steps',           str(MAX_STEPS),\n",
            "    '--diag_period',         str(DIAG_PERIOD),\n",
            "    '--reduced_diag_period', str(REDUCED_PERIOD),\n",
            "    '--reduced_diag_dir',    'reducedfiles/',\n",
            "    '--nx', str(NX), '--ny', str(NY), '--nz', str(NZ),\n",
            "    '--warpx_data_dir',      str(WARPX_DATA_DIR),\n",
            "]\n",
            "print('Command:', ' '.join(cmd))\n",
        ]),
        md(["## 2. Run\n", "\n", "Uncomment `subprocess.run` to start the simulation.\n"]),
        code([
            "# result = subprocess.run(cmd, check=True)\n",
            "# print('Exit code:', result.returncode)\n",
            "print('Ready — uncomment subprocess.run to launch.')\n",
        ]),
        md(["## 3. Load diagnostics\n"]),
        code(PLOT_IMPORTS),
        load_diag_cell("df_vac", "RUNS_DIR / 'vacuum_reference'"),
        md(["## 4. Plots\n", "\n",
            "K_eff/K0 should remain ≈ 1.0 throughout (no compensation).\n"]),
        code([
            "if df_vac is not None:\n",
            "    plot_neutralization_panel(df_vac, PLOTS_DIR, case_name='vacuum_reference')\n",
            "    plot_keff_over_k0(df_vac, PLOTS_DIR, case_name='vacuum_reference')\n",
            "    plt.show()\n",
            "    print('Final K_eff/K0 =', df_vac['keff_over_k0'].iloc[-1])\n",
        ]),
        md(PHYS_CHECKS + ["- [ ] K_eff/K0 ≈ 1.0 (vacuum: no compensation)\n"]),
    ]
    p = NB_RUNS / "nb_vacuum_reference.ipynb"
    p.write_text(json.dumps(notebook(cells), indent=1, ensure_ascii=False))
    print("Written:", p)


# ── seeded run (H2 or Kr) ─────────────────────────────────────────────────────
def make_seeded_nb(gas, pressure, neutralization, fname):
    cn = f"seeded_{gas}"
    cells = [
        md([f"# Seeded Plasma-Column Full Transport — {gas}\n", "\n",
            f"Full-domain seeded neutralization run for **{gas}** at **{pressure} Torr**.\n",
            "\n",
            "> **Caution**: Analytic/data-driven seeded source estimate, not fully\n",
            "> self-consistent proton-impact MCC. Label all results accordingly.\n"]),
        code(COMMON_IMPORTS),
        code([
            "from plasma_column.notebook_utils import print_simulation_config\n",
            "SCRIPT = _ROOT / 'plasma_column_mcc_picmi_v7.py'\n",
            "_DEFAULTS = {\n",
            f"    'script':               'plasma_column_mcc_picmi_v7.py',\n",
            f"    'case':                 '{cn}',\n",
            f"    'gas':                  '{gas}',\n",
            f"    'neutralization':       {neutralization},\n",
            "    'mcc':                  'electron_impact',\n",
            f"    'pressure_torr':        '{pressure}',\n",
            "    'plasma_age [s]':       '2e-4',\n",
            "    'max_steps':            120000,\n",
            "    'diag_period':          5000,\n",
            "    'reduced_diag_period':  100,\n",
            "    'nx / ny / nz':         '32 / 32 / 256',\n",
            "}\n",
            "_OVERRIDES = {}  # e.g. {'max_steps': 500}\n",
            "print_simulation_config(\n",
            f"    notebook_title='Seeded Full Transport — {gas}',\n",
            "    defaults=_DEFAULTS, overrides=_OVERRIDES,\n",
            f"    extra_info={{'output root': str(RUNS_DIR / '{cn}')}},\n",
            ")\n",
        ]),
        md(["## 1. Configure\n"]),
        code([
            "MAX_STEPS      = 120000\n",
            "DIAG_PERIOD    = 5000\n",
            "REDUCED_PERIOD = 100\n",
            "NX, NY, NZ     = 32, 32, 256\n",
            f"OUT_DIR = RUNS_DIR / '{cn}'\n",
            "OUT_DIR.mkdir(parents=True, exist_ok=True)\n",
            "cmd = [\n",
            "    sys.executable, str(SCRIPT), '--run',\n",
            "    '--output_dir',          str(OUT_DIR),\n",
            f"    '--gas',                 '{gas}',\n",
            f"    '--neutralization',      '{neutralization}',\n",
            "    '--mcc',                 'electron_impact',\n",
            f"    '--pressure_torr',       '{pressure}',\n",
            "    '--plasma_age',          '2e-4',\n",
            "    '--max_steps',           str(MAX_STEPS),\n",
            "    '--diag_period',         str(DIAG_PERIOD),\n",
            "    '--reduced_diag_period', str(REDUCED_PERIOD),\n",
            "    '--reduced_diag_dir',    'reducedfiles/',\n",
            "    '--nx', str(NX), '--ny', str(NY), '--nz', str(NZ),\n",
            "    '--warpx_data_dir',      str(WARPX_DATA_DIR),\n",
            "]\n",
            "print('Command:', ' '.join(cmd))\n",
        ]),
        md(["## 2. Run\n"]),
        code(["# result = subprocess.run(cmd, check=True)\n",
              "print('Ready — uncomment subprocess.run to launch.')\n"]),
        md(["## 3. Load diagnostics\n"]),
        code(PLOT_IMPORTS),
        load_diag_cell("df_seeded", f"RUNS_DIR / '{cn}'"),
        md(["## 4. Diagnostic plots\n", "\n",
            "> eta should rise from seed value. K_eff/K0 should decrease.\n"]),
        plot_diag_cell("df_seeded", cn),
        md(PHYS_CHECKS + ["- [ ] Results labelled as analytic/seeded (not self-consistent MCC)\n"]),
        summary_cell("df_seeded", cn, gas, pressure),
    ]
    p = NB_RUNS / fname
    p.write_text(json.dumps(notebook(cells), indent=1, ensure_ascii=False))
    print("Written:", p)


# ── callback run (H2 or Kr) ───────────────────────────────────────────────────
def make_callback_nb(gas, pressure, fname):
    cn = f"callback_{gas}"
    cells = [
        md([f"# Python-Callback Proton-Impact Ionisation Source — {gas}\n", "\n",
            f"Full production run using the **Python callback** source model for **{gas}**.\n",
            "\n",
            "> **Limitation**: Data-driven source estimate — not self-consistent MCC.\n",
            "> Label results accordingly.\n"]),
        code(COMMON_IMPORTS),
        code([
            "from plasma_column.notebook_utils import print_simulation_config\n",
            "SCRIPT = _ROOT / 'plasma_column_callback_source_picmi_v3.py'\n",
            "_DEFAULTS = {\n",
            f"    'script':                'plasma_column_callback_source_picmi_v3.py',\n",
            f"    'case':                  '{cn}',\n",
            f"    'gas':                   '{gas}',\n",
            f"    'pressure_torr':         '{pressure}',\n",
            "    'max_steps':             20000,\n",
            "    'diag_period':           5000,\n",
            "    'reduced_diag_period':   100,\n",
            "    'nx / ny / nz':          '24 / 24 / 128',\n",
            "    'source_every_n_steps':  10,\n",
            "    'enable_ionization_source': 1,\n",
            "}\n",
            "_OVERRIDES = {}  # e.g. {'max_steps': 2000}\n",
            "print_simulation_config(\n",
            f"    notebook_title='Callback Source — {gas}',\n",
            "    defaults=_DEFAULTS, overrides=_OVERRIDES,\n",
            f"    extra_info={{'output root': str(RUNS_DIR / '{cn}')}},\n",
            ")\n",
        ]),
        md(["## 1. Configure\n"]),
        code([
            "MAX_STEPS      = 20000\n",
            "DIAG_PERIOD    = 5000\n",
            "REDUCED_PERIOD = 100\n",
            "NX, NY, NZ     = 24, 24, 128\n",
            f"OUT_DIR = RUNS_DIR / '{cn}'\n",
            "OUT_DIR.mkdir(parents=True, exist_ok=True)\n",
            "cmd = [\n",
            "    sys.executable, str(SCRIPT), '--run',\n",
            "    '--output_dir',             str(OUT_DIR),\n",
            f"    '--gas',                    '{gas}',\n",
            f"    '--pressure_torr',          '{pressure}',\n",
            "    '--max_steps',              str(MAX_STEPS),\n",
            "    '--diag_period',            str(DIAG_PERIOD),\n",
            "    '--reduced_diag_period',    str(REDUCED_PERIOD),\n",
            "    '--reduced_diag_dir',       'reducedfiles/',\n",
            "    '--nx', str(NX), '--ny', str(NY), '--nz', str(NZ),\n",
            "    '--source_every_n_steps',   '10',\n",
            "    '--enable_ionization_source','1',\n",
            "    '--warpx_data_dir',         str(WARPX_DATA_DIR),\n",
            "]\n",
            "print('Command:', ' '.join(cmd))\n",
        ]),
        md(["## 2. Run\n"]),
        code(["# result = subprocess.run(cmd, check=True)\n",
              "print('Ready — uncomment subprocess.run to launch.')\n"]),
        md(["## 3. Load diagnostics\n"]),
        code(PLOT_IMPORTS),
        load_diag_cell("df_cb", f"RUNS_DIR / '{cn}'"),
        md(["## 4. Diagnostic plots\n", "\n",
            "> **Pair-production check**: dNe/dt ≈ dNi/dt expected.\n"]),
        plot_diag_cell("df_cb", cn),
        md(PHYS_CHECKS + [
            "- [ ] dNe/dt ≈ dNi/dt (pair-production validation)\n",
            "- [ ] Cross-section at 30 keV correctly interpolated\n",
            "- [ ] Results labelled as callback/data-driven\n",
        ]),
        summary_cell("df_cb", cn, gas, pressure),
    ]
    p = NB_RUNS / fname
    p.write_text(json.dumps(notebook(cells), indent=1, ensure_ascii=False))
    print("Written:", p)


# ── nb_analysis_plots.ipynb ───────────────────────────────────────────────────
def make_analysis_plots_nb():
    cells = [
        md(["# Plasma-Column Analysis Plots\n", "\n",
            "Auto-discovers completed runs under `runs/`, loads diagnostics,\n",
            "and generates the full publication figure set.\n"]),
        code(COMMON_IMPORTS),
        code([
            "from plasma_column.notebook_utils import print_simulation_config\n",
            "_DEFAULTS = {\n",
            "    'runs root':               str(RUNS_DIR),\n",
            "    'figures root':            str(PLOTS_DIR),\n",
            "    'expected methods':        'vacuum, seeded, callback',\n",
            "    'output format':           'PNG (300 DPI) + PDF',\n",
            "    'beam energy [keV]':       30.0,\n",
            "    'beam current [mA]':       10.0,\n",
            "    'plasma cell length [m]':  0.20,\n",
            "    'inflector aperture [mm]': 5.0,\n",
            "}\n",
            "print_simulation_config(\n",
            "    notebook_title='Plasma-Column Analysis Plots',\n",
            "    defaults=_DEFAULTS, overrides={},\n",
            ")\n",
        ]),
        md(["## 1. Discover and load cases\n"]),
        code(PLOT_IMPORTS),
        code([
            "import warnings\n",
            "\n",
            "def _infer_meta(d):\n",
            "    n = d.name.lower()\n",
            "    return {\n",
            "        'case':   d.name,\n",
            "        'method': ('seeded'   if 'seeded'   in n else\n",
            "                   'callback' if 'callback' in n else\n",
            "                   'vacuum'   if 'vacuum'   in n else 'unknown'),\n",
            "        'gas':    'Kr' if 'kr' in n else 'H2',\n",
            "    }\n",
            "\n",
            "def _find_diag(d):\n",
            "    for p in [d / 'reducedfiles' / 'ParticleNumber_red.txt',\n",
            "               d / 'neutralization_from_particle_number.csv']:\n",
            "        if p.exists(): return p\n",
            "    return None\n",
            "\n",
            "cases = []\n",
            "for case_dir in sorted(RUNS_DIR.iterdir()):\n",
            "    if not case_dir.is_dir(): continue\n",
            "    diag = _find_diag(case_dir)\n",
            "    if diag is None: continue\n",
            "    meta = _infer_meta(case_dir)\n",
            "    with warnings.catch_warnings():\n",
            "        warnings.simplefilter('ignore')\n",
            "        hist = load_particle_number_diagnostic(diag)\n",
            "        hist = compute_particle_number_metrics(hist)\n",
            "    cases.append((case_dir, hist, meta))\n",
            "    print(f\"  {case_dir.name}  ({meta['method']} | {meta['gas']}) — {len(hist)} steps\")\n",
            "print(f'\\nTotal cases loaded: {len(cases)}')\n",
        ]),
        md(["## 2. Multi-case neutralisation overlay\n"]),
        code([
            "multi_pairs = [(f\"{m['case']} | {m['method']} | {m['gas']}\", h)\n",
            "               for _, h, m in cases]\n",
            "for col, ylabel, oname in [\n",
            "    ('eta_net',           r'$(N_e-N_i)/N_p$',   'all_eta_net'),\n",
            "    ('eta_electron_only', r'$N_e/N_p$',           'all_eta_electron'),\n",
            "    ('keff_over_k0',      r'$K_{\\rm eff}/K_0$',  'all_keff'),\n",
            "]:\n",
            "    if not any(col in h.columns for _, h, _ in cases): continue\n",
            "    p, _ = plot_multi_case_neutralization(\n",
            "        multi_pairs, PLOTS_DIR, column=col,\n",
            "        ylabel=ylabel, title=f'All cases — {ylabel}', output_name=oname,\n",
            "    )\n",
            "    print('Saved:', p.name)\n",
            "plt.show()\n",
        ]),
        md(["## 3. Per-case 3-panel summary\n"]),
        code([
            "for _, hist, meta in cases:\n",
            "    p, _ = plot_neutralization_panel(hist, PLOTS_DIR, case_name=meta['case'])\n",
            "    print('Saved:', p.name)\n",
            "plt.show()\n",
        ]),
        md(["## 4. Species growth rates\n"]),
        code([
            "for _, hist, meta in cases:\n",
            "    if not {'Ne','Ni'}.issubset(hist.columns): continue\n",
            "    p, _ = plot_species_growth_rates(hist, PLOTS_DIR,\n",
            "                                     case_name=meta['case'], smooth_window=7)\n",
            "    print('Saved:', p.name)\n",
            "plt.show()\n",
        ]),
        md(["## 5. Bunched-beam perveance\n"]),
        code([
            "for _, hist, meta in cases:\n",
            "    if 'eta_net' not in hist.columns: continue\n",
            "    p, _ = plot_bunched_beam_keff(\n",
            "        hist['time'].values * 1e9,\n",
            "        hist['eta_net'].values.clip(0, 1), PLOTS_DIR,\n",
            "        case_name=meta['case'],\n",
            "        bunching_factors=[1.0, 2.0, 3.0, 5.0, 8.0],\n",
            "    )\n",
            "    print('Saved:', p.name)\n",
            "plt.show()\n",
        ]),
        md(["## 6. Final-value summary table\n"]),
        code([
            "rows = []\n",
            "for _, hist, meta in cases:\n",
            "    row = dict(meta)\n",
            "    for col in ['eta_electron_only', 'eta_net', 'keff_over_k0']:\n",
            "        row[f'final_{col}'] = hist[col].iloc[-1] if col in hist.columns else float('nan')\n",
            "    row['n_steps'] = len(hist)\n",
            "    rows.append(row)\n",
            "display(pd.DataFrame(rows))\n",
        ]),
    ]
    p = NB_ANALYSIS / "nb_analysis_plots.ipynb"
    p.write_text(json.dumps(notebook(cells), indent=1, ensure_ascii=False))
    print("Written:", p)


# ── nb_bunched_beam_perveance.ipynb ───────────────────────────────────────────
def make_bb_perveance_nb():
    cells = [
        md(["# Bunched-Beam Effective Perveance Analysis\n", "\n",
            "$$K_{\\rm eff,peak}/K_0 \\approx 1 - \\bar{\\eta}/B_f$$\n", "\n",
            "Primary interpretation limit for any H2/Kr neutralisation result.\n"]),
        code(COMMON_IMPORTS),
        code([
            "from plasma_column.notebook_utils import print_simulation_config\n",
            "_DEFAULTS = {\n",
            "    'beam energy [keV]':       30.0,\n",
            "    'beam current [mA]':       10.0,\n",
            "    'bunching factors B_f':    '1, 2, 3, 5, 8',\n",
            "    'f_RF [MHz]':              72.0,\n",
            "    'bunch phase width [deg]': 30.0,\n",
            "}\n",
            "print_simulation_config(\n",
            "    notebook_title='Bunched-Beam Effective Perveance',\n",
            "    defaults=_DEFAULTS, overrides={},\n",
            ")\n",
        ]),
        md(["## 1. Beam parameters\n"]),
        code([
            "import math\n",
            "from plasma_column.beam import ProtonBeam\n",
            "from plasma_column.plotting import setup_publication_style, plot_bunched_beam_keff\n",
            "setup_publication_style()\n",
            "\n",
            "beam = ProtonBeam(energy_keV=30.0, current_mA=10.0, radius_m=2e-3)\n",
            "K0   = beam.perveance_K0\n",
            "B_f_values = [1.0, 2.0, 3.0, 5.0, 8.0]\n",
            "f_RF_MHz, phase_width_deg = 72.0, 30.0\n",
            "T_RF = 1.0 / (f_RF_MHz * 1e6)\n",
            "dt_b = (phase_width_deg / 360.0) * T_RF\n",
            "dz_b = beam.velocity * dt_b\n",
            "print(f'K0={K0:.4e}  beta={beam.beta:.6f}  v={beam.velocity:.4e} m/s')\n",
            "print(f'T_RF={T_RF*1e9:.3f} ns  dt_b={dt_b*1e9:.3f} ns  dz_b={dz_b*1e3:.2f} mm')\n",
        ]),
        md(["## 2. Load eta_avg(t) from first available run\n"]),
        code([
            "import warnings\n",
            "from plasma_column.diagnostics import load_particle_number_diagnostic, compute_particle_number_metrics\n",
            "\n",
            "_hist = None\n",
            "for _cd in sorted(RUNS_DIR.iterdir()):\n",
            "    for _p in [_cd / 'reducedfiles' / 'ParticleNumber_red.txt',\n",
            "                _cd / 'neutralization_from_particle_number.csv']:\n",
            "        if _p.exists():\n",
            "            with warnings.catch_warnings():\n",
            "                warnings.simplefilter('ignore')\n",
            "                _hist = compute_particle_number_metrics(\n",
            "                    load_particle_number_diagnostic(_p))\n",
            "            print(f'Using: {_cd.name} ({len(_hist)} steps)')\n",
            "            break\n",
            "    if _hist is not None: break\n",
            "\n",
            "if _hist is None:\n",
            "    print('No runs found — using synthetic ramp.')\n",
            "    _t_ns    = np.linspace(0, 400, 300)\n",
            "    _eta_avg = np.clip(np.linspace(0, 0.75, 300), 0, 1)\n",
            "else:\n",
            "    _t_ns    = _hist['time'].values * 1e9\n",
            "    _eta_avg = _hist['eta_net'].values.clip(0, 1)\n",
        ]),
        code([
            "p, _ = plot_bunched_beam_keff(\n",
            "    _t_ns, _eta_avg, PLOTS_DIR,\n",
            "    case_name='bunched_beam_analysis',\n",
            "    bunching_factors=B_f_values,\n",
            ")\n",
            "plt.show()\n",
            "print('Saved:', p.name)\n",
        ]),
        md(["## 3. Final K_eff,peak table\n"]),
        code([
            "eta_f = float(_eta_avg[-1])\n",
            "rows  = [{'B_f': Bf, 'eta_avg_final': eta_f,\n",
            "           'K_eff_peak_over_K0': max(0.0, 1.0 - eta_f / Bf)}\n",
            "          for Bf in B_f_values]\n",
            "display(pd.DataFrame(rows).set_index('B_f').style.format('{:.4f}'))\n",
        ]),
    ]
    p = NB_ANALYSIS / "nb_bunched_beam_perveance.ipynb"
    p.write_text(json.dumps(notebook(cells), indent=1, ensure_ascii=False))
    print("Written:", p)


# ── nb_cross_section_comparison.ipynb ────────────────────────────────────────
def make_xs_nb():
    cells = [
        md(["# H2 vs Kr Proton-Impact Ionisation Cross-Section Comparison\n", "\n",
            "Loads tabulated cross sections, plots sigma(E), and highlights the 30 keV point.\n"]),
        code(COMMON_IMPORTS),
        code([
            "from plasma_column.notebook_utils import print_simulation_config\n",
            "_DEFAULTS = {\n",
            "    'beam energy [keV]':   30.0,\n",
            "    'cross-section source':'warpx-data/MCC_cross_sections/',\n",
            "    'gases':               'H2, Kr',\n",
            "    'energy range [keV]':  '1 - 1000',\n",
            "}\n",
            "print_simulation_config(\n",
            "    notebook_title='H2 vs Kr Cross-Section Comparison',\n",
            "    defaults=_DEFAULTS, overrides={},\n",
            ")\n",
        ]),
        md(["## 1. Plot sigma(E)\n"]),
        code([
            "from plasma_column.gas import load_cross_section_table, get_h2_cross_section, get_kr_cross_section\n",
            "from plasma_column.plotting import setup_publication_style, save_figure\n",
            "setup_publication_style()\n",
            "\n",
            "BEAM_KEV = 30.0\n",
            "XS_ROOT  = WARPX_DATA_DIR / 'MCC_cross_sections'\n",
            "GAS_META = {\n",
            "    'H2': {'path': XS_ROOT / 'H2' / 'proton_impact_ionization.dat',\n",
            "           'color': 'tab:blue',   'label': r'H$_2$'},\n",
            "    'Kr': {'path': XS_ROOT / 'Kr' / 'proton_impact_ionization.dat',\n",
            "           'color': 'tab:orange', 'label': 'Kr'},\n",
            "}\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(9, 5))\n",
            "for gas, meta in GAS_META.items():\n",
            "    if not meta['path'].exists():\n",
            "        print(f'{gas}: not found — {meta[\"path\"]}')\n",
            "        continue\n",
            "    df_xs = load_cross_section_table(meta['path'])\n",
            "    ax.loglog(df_xs.iloc[:,0] * 1e-3, df_xs.iloc[:,1],\n",
            "              color=meta['color'], lw=2, label=meta['label'])\n",
            "\n",
            "ax.axvline(BEAM_KEV, color='gray', lw=1.2, ls='--',\n",
            "           label=f'{BEAM_KEV:.0f} keV operating point')\n",
            "ax.set_xlabel('Proton kinetic energy [keV]', fontsize=12)\n",
            "ax.set_ylabel(r'Cross section [m$^2$]', fontsize=12)\n",
            "ax.set_title(r'Proton-impact ionisation: H$_2$ vs Kr', fontsize=13)\n",
            "ax.legend(fontsize=10)\n",
            "ax.grid(True, ls='--', alpha=0.5, which='both')\n",
            "p, _ = save_figure(fig, PLOTS_DIR / 'h2_kr_cross_sections')\n",
            "plt.show()\n",
            "print('Saved:', p.name)\n",
        ]),
        md(["## 2. Operating-point read-out\n"]),
        code([
            "s_h2 = get_h2_cross_section(BEAM_KEV)\n",
            "s_kr = get_kr_cross_section(BEAM_KEV)\n",
            "print(f'sigma(H2, {BEAM_KEV} keV) = {s_h2:.4e} m2')\n",
            "print(f'sigma(Kr, {BEAM_KEV} keV) = {s_kr:.4e} m2')\n",
            "print(f'Ratio sigma_Kr / sigma_H2  = {s_kr/s_h2:.2f}')\n",
        ]),
    ]
    p = NB_ANALYSIS / "nb_cross_section_comparison.ipynb"
    p.write_text(json.dumps(notebook(cells), indent=1, ensure_ascii=False))
    print("Written:", p)


# ── nb_local_neutralization_profiles.ipynb ───────────────────────────────────
def make_local_profiles_nb():
    cells = [
        md(["# Local Neutralisation Profiles — Radial and Axial\n", "\n",
            "Core-averaged density profiles and eta(z) from 3-D WarpX field arrays.\n", "\n",
            "> Global ParticleNumber ratios are necessary but **not sufficient** to claim\n",
            "> local space-charge compensation. This notebook provides spatial evidence.\n"]),
        code(COMMON_IMPORTS),
        code([
            "from plasma_column.notebook_utils import print_simulation_config\n",
            "_DEFAULTS = {\n",
            "    'plasma cell z-range [m]':  '0.00 - 0.20',\n",
            "    'beam-core radius [mm]':    2.0,\n",
            "    'r_max for profiles [mm]':  15.0,\n",
            "    'radial bins':              60,\n",
            "    'grid (synthetic)':         '31 x 31 x 50',\n",
            "    'eta_target (synthetic)':   0.70,\n",
            "}\n",
            "print_simulation_config(\n",
            "    notebook_title='Local Neutralisation Profiles',\n",
            "    defaults=_DEFAULTS, overrides={},\n",
            ")\n",
        ]),
        md(["## 1. 3-D density arrays (synthetic demo)\n", "\n",
            "Replace `ne_3d, ni_3d, np_3d, x, y, z` with arrays from a WarpX plotfile\n",
            "(e.g. via `yt`) for production use.\n"]),
        code([
            "from plasma_column.plotting import (\n",
            "    setup_publication_style, plot_radial_density_profile, plot_neutralization_vs_z,\n",
            ")\n",
            "from plasma_column.diagnostics import (\n",
            "    generate_synthetic_3d_grid,\n",
            "    compute_radial_density_profiles,\n",
            "    compute_local_neutralization_vs_z,\n",
            "    compute_local_core_neutralization,\n",
            ")\n",
            "setup_publication_style()\n",
            "\n",
            "ETA_TARGET = 0.70\n",
            "R_CORE_M   = 0.002\n",
            "\n",
            "ne_3d, ni_3d, np_3d, x, y, z = generate_synthetic_3d_grid(\n",
            "    nx=31, ny=31, nz=50, n_proton_peak=1e15, eta_target=ETA_TARGET,\n",
            ")\n",
            "print('Grid shape:', ne_3d.shape, '  z:', f'{z[0]:.3f} - {z[-1]:.3f} m')\n",
        ]),
        md(["## 2. Radial density profiles\n"]),
        code([
            "radial_df = compute_radial_density_profiles(\n",
            "    ne_3d, ni_3d, np_3d, x, y, z,\n",
            "    z_min_col=0.0, z_max_col=0.20, r_max=0.015, n_bins=60,\n",
            ")\n",
            "p, _ = plot_radial_density_profile(\n",
            "    radial_df, PLOTS_DIR,\n",
            "    case_name='local_profiles_demo', highlight_core_r=R_CORE_M,\n",
            ")\n",
            "plt.show()\n",
            "print('Saved:', p.name)\n",
            "display(radial_df.head())\n",
        ]),
        md(["## 3. Axial neutralisation profile eta(z)\n"]),
        code([
            "z_df = compute_local_neutralization_vs_z(\n",
            "    ne_3d, ni_3d, np_3d, x, y, z, r_core=R_CORE_M,\n",
            ")\n",
            "p, _ = plot_neutralization_vs_z(\n",
            "    z_df, PLOTS_DIR, case_name='local_profiles_demo', z_col_range=(0.0, 0.20),\n",
            ")\n",
            "plt.show()\n",
            "print('Saved:', p.name)\n",
            "display(z_df[['z','eta_electron_only_local_z','eta_net_local_z','keff_over_k0_local_z']].head(10))\n",
        ]),
        md(["## 4. Core-volume summary\n"]),
        code([
            "core = compute_local_core_neutralization(\n",
            "    ne_3d, ni_3d, np_3d, x, y, z,\n",
            "    z_min_col=0.0, z_max_col=0.20, r_core=R_CORE_M,\n",
            ")\n",
            "print('Core-averaged diagnostics:')\n",
            "for k, v in core.items():\n",
            "    print(f'  {k:<38} {v:.4g}')\n",
        ]),
    ]
    p = NB_ANALYSIS / "nb_local_neutralization_profiles.ipynb"
    p.write_text(json.dumps(notebook(cells), indent=1, ensure_ascii=False))
    print("Written:", p)





# ══════════════════════════════════════════════════════════════════════════════
# notebooks/runs/nb_parameter_scan.ipynb
# ══════════════════════════════════════════════════════════════════════════════
def make_parameter_scan_run_nb():
    cells = [
        md(["# Parameter Scan — Launch and Monitor\n", "\n",
            "Defines and launches a parameter scan matrix using `ScanMatrix` from\n",
            "`plasma_column.run_matrix`. Each (gas, method, pressure) combination\n",
            "becomes an independent case directory under `runs/`.\n",
            "\n",
            "**Scan axes covered**:\n",
            "- Gas species: H2, Kr\n",
            "- Gas pressure: 1e-6 → 3e-4 Torr (6 points, log-spaced)\n",
            "- Method: seeded, callback *(add or remove in §1)*\n",
            "\n",
            "> Set `DRY_RUN = True` to validate commands without launching WarpX.\n",
            "> Set `DRY_RUN = False` to execute all cases sequentially.\n",
            "> For parallel execution, use `scripts/run_scan.py` with a job scheduler.\n"]),
        code(COMMON_IMPORTS),
        code([
            "from plasma_column.notebook_utils import print_simulation_config\n",
            "from plasma_column.run_matrix import ScanMatrix, ScanParameter, build_scan_dataframe, run_scan_matrix\n",
            "\n",
            "_DEFAULTS = {\n",
            "    'scan_name':       'pressure_scan_h2_kr',\n",
            "    'gases':           'H2, Kr',\n",
            "    'pressures [Torr]':'1e-6, 3e-6, 1e-5, 3e-5, 1e-4, 3e-4',\n",
            "    'methods':         'seeded, callback',\n",
            "    'beam energy [keV]':30.0,\n",
            "    'beam current [mA]':10.0,\n",
            "    'max_steps (smoke)':500,\n",
            "    'max_steps (full)': 120000,\n",
            "    'grid (seeded)':   '32 x 32 x 256',\n",
            "    'grid (callback)': '24 x 24 x 128',\n",
            "}\n",
            "_OVERRIDES = {}  # e.g. restrict to one gas or fewer pressures\n",
            "print_simulation_config(\n",
            "    notebook_title='Parameter Scan — Launch and Monitor',\n",
            "    defaults=_DEFAULTS, overrides=_OVERRIDES,\n",
            ")\n",
        ]),
        md(["## 1. Define scan matrix\n"]),
        code([
            "DRY_RUN = True   # change to False to run simulations\n",
            "\n",
            "SCRIPT_SEEDED   = _ROOT / 'plasma_column_mcc_picmi_v7.py'\n",
            "SCRIPT_CALLBACK = _ROOT / 'plasma_column_callback_source_picmi_v3.py'\n",
            "\n",
            "# Pressure axis (6 log-spaced points)\n",
            "PRESSURES = [1e-6, 3e-6, 1e-5, 3e-5, 1e-4, 3e-4]  # Torr\n",
            "\n",
            "# Smoke-test settings (small grid, few steps)\n",
            "SMOKE_MAX_STEPS = 500\n",
            "PROD_MAX_STEPS  = 120000\n",
            "\n",
            "# Switch between smoke test and production:\n",
            "MAX_STEPS = SMOKE_MAX_STEPS  # → change to PROD_MAX_STEPS for real runs\n",
            "\n",
            "scan_seeded = ScanMatrix(\n",
            "    scan_name  = 'pressure_scan',\n",
            "    script     = SCRIPT_SEEDED,\n",
            "    parameters = [ScanParameter('pressure_torr', PRESSURES)],\n",
            "    fixed      = {\n",
            "        'neutralization': '0.5',\n",
            "        'mcc':            'electron_impact',\n",
            "        'plasma_age':     '2e-4',\n",
            "        'max_steps':       MAX_STEPS,\n",
            "        'diag_period':     max(100, MAX_STEPS // 24),\n",
            "        'reduced_diag_period': 100,\n",
            "        'nx': 32, 'ny': 32, 'nz': 256,\n",
            "    },\n",
            "    gases   = ['H2', 'Kr'],\n",
            "    methods = ['seeded'],\n",
            "    dry_run = DRY_RUN,\n",
            "    runs_root = RUNS_DIR,\n",
            ")\n",
            "\n",
            "scan_callback = ScanMatrix(\n",
            "    scan_name  = 'callback_scan',\n",
            "    script     = SCRIPT_CALLBACK,\n",
            "    parameters = [ScanParameter('pressure_torr', PRESSURES)],\n",
            "    fixed      = {\n",
            "        'max_steps':              min(20000, MAX_STEPS),\n",
            "        'diag_period':            max(100, min(20000, MAX_STEPS) // 4),\n",
            "        'reduced_diag_period':    100,\n",
            "        'source_every_n_steps':   10,\n",
            "        'enable_ionization_source': 1,\n",
            "        'nx': 24, 'ny': 24, 'nz': 128,\n",
            "    },\n",
            "    gases   = ['H2', 'Kr'],\n",
            "    methods = ['callback'],\n",
            "    dry_run = DRY_RUN,\n",
            "    runs_root = RUNS_DIR,\n",
            ")\n",
            "\n",
            "df_seeded   = build_scan_dataframe(scan_seeded)\n",
            "df_callback = build_scan_dataframe(scan_callback)\n",
            "df_all_cases = pd.concat([df_seeded, df_callback], ignore_index=True)\n",
            "print(f'Total cases: {len(df_all_cases)}')\n",
            "df_all_cases[['case_name','gas','method','pressure_torr']]\n",
        ]),
        md(["## 2. Validate scan with YAML launcher (dry-run)\n"]),
        code([
            "import subprocess\n",
            "# Validate using the YAML-driven script/run_scan.py (no simulation execution)\n",
            "result = subprocess.run(\n",
            "    [sys.executable, 'scripts/run_scan.py',\n",
            "     '--matrix', 'cases/pressure_scan_h2_kr.yaml', '--dry_run'],\n",
            "    capture_output=True, text=True, cwd=str(_ROOT)\n",
            ")\n",
            "print(result.stdout)\n",
            "if result.returncode != 0:\n",
            "    print('STDERR:', result.stderr)\n",
        ]),
        md(["## 3. Launch scan\n", "\n",
            "Uncomment the `run_scan_matrix()` calls to execute cases sequentially.\n",
            "Each call blocks until all cases for that matrix finish.\n"]),
        code([
            "# ── Seeded pressure scan ─────────────────────────────────────────────────\n",
            "# results_seeded = run_scan_matrix(\n",
            "#     df_seeded, scan_seeded,\n",
            "#     warpx_data_dir=WARPX_DATA_DIR,\n",
            "# )\n",
            "\n",
            "# ── Callback pressure scan ───────────────────────────────────────────────\n",
            "# results_callback = run_scan_matrix(\n",
            "#     df_callback, scan_callback,\n",
            "#     warpx_data_dir=WARPX_DATA_DIR,\n",
            "# )\n",
            "\n",
            "print('Launch cells ready — uncomment run_scan_matrix() calls to start.')\n",
        ]),
        md(["## 4. Monitor progress\n"]),
        code([
            "# Count how many cases have completed diagnostic files\n",
            "from plasma_column.run_matrix import _find_diag\n",
            "\n",
            "completed, pending = [], []\n",
            "for _, row in df_all_cases.iterrows():\n",
            "    d = RUNS_DIR / row['case_name']\n",
            "    if _find_diag(d) is not None:\n",
            "        completed.append(row['case_name'])\n",
            "    else:\n",
            "        pending.append(row['case_name'])\n",
            "\n",
            "print(f'Completed: {len(completed)}/{len(df_all_cases)}')\n",
            "for c in completed: print(f'  ✓ {c}')\n",
            "print(f'Pending:   {len(pending)}')\n",
            "for p in pending:   print(f'  … {p}')\n",
        ]),
    ]
    out = NB_RUNS / "nb_parameter_scan.ipynb"
    out.write_text(json.dumps(notebook(cells), indent=1, ensure_ascii=False))
    print("Written:", out)


# ══════════════════════════════════════════════════════════════════════════════
# notebooks/analysis/nb_parameter_scan_analysis.ipynb
# ══════════════════════════════════════════════════════════════════════════════
def make_parameter_scan_analysis_nb():
    cells = [
        md(["# Parameter Scan Analysis and Comparison Visualisation\n", "\n",
            "Loads completed scan results from `runs/`, builds a summary DataFrame,\n",
            "and generates the full suite of comparison visualisations:\n",
            "\n",
            "| § | Plot | Function |\n",
            "|---|------|----------|\n",
            "| 3 | η vs pressure (line) | `plot_scan_eta_vs_pressure` |\n",
            "| 4 | K_eff vs pressure (line) | `plot_scan_keff_vs_pressure` |\n",
            "| 5 | Method comparison bar chart | `plot_scan_method_comparison_bar` |\n",
            "| 6 | K_eff × pressure heatmap | `plot_scan_heatmap` |\n",
            "| 7 | Small-multiple η(t) grid | `plot_scan_neutralization_timeseries_grid` |\n",
            "| 8 | Final η grouped by gas | `plot_scan_final_eta_bar_by_gas` |\n",
            "| 9 | Bunched-beam K_eff,peak | `plot_bunched_beam_keff` (multi-case) |\n",
            "\n",
            "> **Note**: Cells work on any completed subset — no results means synthetic\n",
            "> fallback data is used so the notebook always renders end-to-end.\n"]),
        code(COMMON_IMPORTS),
        code([
            "from plasma_column.notebook_utils import print_simulation_config\n",
            "_DEFAULTS = {\n",
            "    'runs root':               str(RUNS_DIR),\n",
            "    'figures root':            str(PLOTS_DIR),\n",
            "    'scan YAML (pressure)':    'cases/pressure_scan_h2_kr.yaml',\n",
            "    'scan YAML (method)':      'cases/method_scan_baseline.yaml',\n",
            "    't_avg window (frac)':     0.25,\n",
            "    'beam energy [keV]':       30.0,\n",
            "    'bunching factors':        '1, 2, 3, 5, 8',\n",
            "}\n",
            "print_simulation_config(\n",
            "    notebook_title='Parameter Scan Analysis',\n",
            "    defaults=_DEFAULTS, overrides={},\n",
            ")\n",
        ]),
        md(["## 1. Import scan functions\n"]),
        code([
            "import warnings\n",
            "from plasma_column.run_matrix import (\n",
            "    ScanMatrix, ScanParameter,\n",
            "    build_scan_dataframe,\n",
            "    collect_scan_results,\n",
            "    save_scan_summary,\n",
            "    load_scan_summary,\n",
            ")\n",
            "from plasma_column.plotting import (\n",
            "    setup_publication_style,\n",
            "    plot_scan_eta_vs_pressure,\n",
            "    plot_scan_keff_vs_pressure,\n",
            "    plot_scan_method_comparison_bar,\n",
            "    plot_scan_heatmap,\n",
            "    plot_scan_neutralization_timeseries_grid,\n",
            "    plot_scan_final_eta_bar_by_gas,\n",
            "    plot_bunched_beam_keff,\n",
            "    plot_multi_case_neutralization,\n",
            ")\n",
            "from plasma_column.diagnostics import (\n",
            "    load_particle_number_diagnostic,\n",
            "    compute_particle_number_metrics,\n",
            ")\n",
            "setup_publication_style()\n",
            "print('Scan analysis helpers loaded.')\n",
        ]),
        md(["## 2. Build scan index and collect results\n",
            "\n",
            "Constructs the expected scan DataFrame from the YAML configs, then\n",
            "calls `collect_scan_results()` to load whatever has finished.\n",
            "Missing cases show NaN; already-complete cases are loaded automatically.\n"]),
        code([
            "PRESSURES = [1e-6, 3e-6, 1e-5, 3e-5, 1e-4, 3e-4]\n",
            "\n",
            "# Pressure scan index (seeded)\n",
            "_scan_s = ScanMatrix(\n",
            "    scan_name='pressure_scan', script=_ROOT/'plasma_column_mcc_picmi_v7.py',\n",
            "    parameters=[ScanParameter('pressure_torr', PRESSURES)],\n",
            "    gases=['H2','Kr'], methods=['seeded'], runs_root=RUNS_DIR,\n",
            ")\n",
            "# Pressure scan index (callback)\n",
            "_scan_c = ScanMatrix(\n",
            "    scan_name='callback_scan', script=_ROOT/'plasma_column_callback_source_picmi_v3.py',\n",
            "    parameters=[ScanParameter('pressure_torr', PRESSURES)],\n",
            "    gases=['H2','Kr'], methods=['callback'], runs_root=RUNS_DIR,\n",
            ")\n",
            "\n",
            "df_index = pd.concat([\n",
            "    build_scan_dataframe(_scan_s),\n",
            "    build_scan_dataframe(_scan_c),\n",
            "], ignore_index=True)\n",
            "\n",
            "with warnings.catch_warnings():\n",
            "    warnings.simplefilter('ignore')\n",
            "    summary = collect_scan_results(df_index, RUNS_DIR)\n",
            "\n",
            "ok = summary[summary['status']=='ok']\n",
            "print(f'Cases found: {len(ok)}/{len(summary)}')\n",
            "summary[['case_name','gas','method','pressure_torr',\n",
            "         'final_eta_net','final_keff_over_k0','status']]\n",
        ]),
        code([
            "# Save summary CSV for later use\n",
            "_csv = RUNS_DIR.parent / 'plots' / 'scan_summary.csv'\n",
            "if len(ok) > 0:\n",
            "    save_scan_summary(summary, _csv)\n",
            "    print('Saved summary →', _csv)\n",
            "\n",
            "# ── Synthetic fallback when no runs exist yet ─────────────────────────────\n",
            "# This ensures every plot cell below renders even before simulations finish.\n",
            "if len(ok) == 0:\n",
            "    print('No completed cases — using SYNTHETIC fallback data.')\n",
            "    _rows = []\n",
            "    for gas, eta_scale in [('H2',0.60),('Kr',0.87)]:\n",
            "        for method, boost in [('seeded',1.0),('callback',1.15)]:\n",
            "            for p in PRESSURES:\n",
            "                eta = float(np.clip(eta_scale * boost * (p/1e-5)**0.45, 0, 0.99))\n",
            "                _rows.append({'case_name':f'{method}_{gas}_{p:.0e}',\n",
            "                               'gas':gas,'method':method,'pressure_torr':p,\n",
            "                               'final_eta_net':eta,'final_eta_electron_only':eta*0.95,\n",
            "                               'final_keff_over_k0':1-eta,'avg_eta_net':eta*0.9,\n",
            "                               'status':'synthetic'})\n",
            "    summary = pd.DataFrame(_rows)\n",
            "    ok = summary\n",
            "    print(f'Synthetic summary built ({len(summary)} rows)')\n",
        ]),
        md(["## 3. η_net vs pressure — line plot\n",
            "\n",
            "Primary result: how fast neutralisation saturates as pressure increases.\n",
            "H₂ and Kr are expected to converge toward η=1 at high pressure but with\n",
            "different rates due to their cross-section magnitudes.\n"]),
        code([
            "p, _ = plot_scan_eta_vs_pressure(\n",
            "    summary, PLOTS_DIR,\n",
            "    eta_col='final_eta_net',\n",
            "    title=r'Final $\\eta_{\\rm net}$ vs Gas Pressure — H$_2$ and Kr',\n",
            "    output_name='scan_eta_vs_pressure',\n",
            ")\n",
            "plt.show()\n",
            "print('Saved:', p.name)\n",
        ]),
        md(["## 4. K_eff/K0 vs pressure — line plot\n",
            "\n",
            "Companion to §3: shows the perveance reduction directly.\n",
            "The target is K_eff/K0 < 0.5 (>50% reduction) at the operating pressure.\n"]),
        code([
            "p, _ = plot_scan_keff_vs_pressure(\n",
            "    summary, PLOTS_DIR,\n",
            "    keff_col='final_keff_over_k0',\n",
            "    title=r'$K_{\\rm eff}/K_0$ vs Pressure — Seeded and Callback Methods',\n",
            "    output_name='scan_keff_vs_pressure',\n",
            ")\n",
            "plt.show()\n",
            "print('Saved:', p.name)\n",
        ]),
        md(["## 5. Method comparison bar chart\n",
            "\n",
            "Side-by-side final K_eff/K0 for every case at a glance.\n",
            "Bars coloured by gas; sorted by case_name.\n"]),
        code([
            "p, _ = plot_scan_method_comparison_bar(\n",
            "    summary.sort_values(['method','gas','pressure_torr']),\n",
            "    PLOTS_DIR,\n",
            "    metric_col='final_keff_over_k0',\n",
            "    ylabel=r'$K_{\\rm eff}/K_0$',\n",
            "    title='Method and Pressure Comparison — Final Effective Perveance',\n",
            "    output_name='scan_method_comparison_bar',\n",
            ")\n",
            "plt.show()\n",
            "print('Saved:', p.name)\n",
        ]),
        md(["## 6. Parameter scan heatmap: gas × pressure\n",
            "\n",
            "2-D colour map: rows = gas, columns = pressure. Cell colour and value\n",
            "show K_eff/K0. Green = well-compensated; red = poor.\n",
            "Use `row_col='method'` to pivot by method instead.\n"]),
        code([
            "for method in summary['method'].unique():\n",
            "    sub = summary[summary['method']==method].copy()\n",
            "    if len(sub) < 2: continue\n",
            "    p, _ = plot_scan_heatmap(\n",
            "        sub, PLOTS_DIR,\n",
            "        row_col='gas', col_col='pressure_torr',\n",
            "        value_col='final_keff_over_k0',\n",
            "        title=fr'$K_{{\\rm eff}}/K_0$ Heatmap — {method} method',\n",
            "        output_name=f'scan_heatmap_{method}',\n",
            "    )\n",
            "    plt.show()\n",
            "    print('Saved:', p.name)\n",
        ]),
        md(["## 7. Small-multiple η(t) grid — all scan cases\n",
            "\n",
            "One mini-panel per case shows the neutralisation build-up trajectory.\n",
            "All panels share the y-axis (0–1) for easy comparison.\n",
            "Cases without diagnostic data show empty panels.\n"]),
        code([
            "# Load time-series for all completed cases\n",
            "ts_pairs = []\n",
            "for _, row in summary.iterrows():\n",
            "    out_d = RUNS_DIR / row['case_name']\n",
            "    from plasma_column.run_matrix import _find_diag\n",
            "    diag = _find_diag(out_d)\n",
            "    if diag is None:\n",
            "        # Synthetic time-series for demonstration\n",
            "        _t = np.linspace(0, 400e-9, 150)\n",
            "        eta_f = row.get('final_eta_net', 0.5)\n",
            "        _eta  = eta_f * (1 - np.exp(-_t / (120e-9)))\n",
            "        _df = pd.DataFrame({'time': _t, 'eta_net': _eta})\n",
            "    else:\n",
            "        with warnings.catch_warnings():\n",
            "            warnings.simplefilter('ignore')\n",
            "            _df = compute_particle_number_metrics(\n",
            "                load_particle_number_diagnostic(diag))\n",
            "    label = f\"{row['gas']} | {row['method']} | {row['pressure_torr']:.1e} Torr\"\n",
            "    ts_pairs.append((label, _df))\n",
            "\n",
            "if ts_pairs:\n",
            "    p, _ = plot_scan_neutralization_timeseries_grid(\n",
            "        ts_pairs, PLOTS_DIR, ncols=4,\n",
            "        output_name='scan_timeseries_grid',\n",
            "        title='Neutralisation Build-up — All Scan Cases',\n",
            "    )\n",
            "    plt.show()\n",
            "    print('Saved:', p.name)\n",
        ]),
        md(["## 8. Final η grouped by gas and method (bar)\n",
            "\n",
            "Clusters show the gas comparison within each method.\n",
            "Use `group_col='gas'` to flip and cluster by gas instead.\n"]),
        code([
            "p, _ = plot_scan_final_eta_bar_by_gas(\n",
            "    summary, PLOTS_DIR,\n",
            "    eta_col='final_eta_net',\n",
            "    group_col='method',\n",
            "    title='Final Neutralisation — Grouped by Method and Gas',\n",
            "    output_name='scan_final_eta_bar',\n",
            ")\n",
            "plt.show()\n",
            "print('Saved:', p.name)\n",
        ]),
        md(["## 9. Bunched-beam K_eff,peak at best operating point\n",
            "\n",
            "Selects the case with the highest η_net and plots\n",
            "K_eff,peak/K0 for B_f = 1…8 as the final quantitative result.\n",
            "\n",
            "**Interpretation**: even at η̄ = 0.9, a bunching factor of 5 leaves\n",
            "K_eff,peak/K0 ≈ 0.82 — a significant residual space-charge load.\n"]),
        code([
            "# Select best case by lowest final_keff_over_k0\n",
            "best_row = summary.loc[summary['final_keff_over_k0'].idxmin()]\n",
            "best_name = best_row['case_name']\n",
            "print(f'Best case: {best_name}  K_eff/K0 = {best_row[\"final_keff_over_k0\"]:.4f}')\n",
            "\n",
            "# Load its time-series (or use synthetic)\n",
            "_d = RUNS_DIR / best_name\n",
            "from plasma_column.run_matrix import _find_diag\n",
            "_diag = _find_diag(_d)\n",
            "if _diag is not None:\n",
            "    with warnings.catch_warnings():\n",
            "        warnings.simplefilter('ignore')\n",
            "        _best_hist = compute_particle_number_metrics(\n",
            "            load_particle_number_diagnostic(_diag))\n",
            "    _t_ns    = _best_hist['time'].values * 1e9\n",
            "    _eta_avg = _best_hist['eta_net'].values.clip(0, 1)\n",
            "else:\n",
            "    _t_ns    = np.linspace(0, 400, 200)\n",
            "    eta_f    = float(best_row['final_eta_net'])\n",
            "    _eta_avg = eta_f * (1 - np.exp(-_t_ns / 120))\n",
            "    print('(using synthetic time-series for best case)')\n",
            "\n",
            "p, _ = plot_bunched_beam_keff(\n",
            "    _t_ns, _eta_avg, PLOTS_DIR,\n",
            "    case_name=f'best_case_{best_name}',\n",
            "    bunching_factors=[1.0, 2.0, 3.0, 5.0, 8.0],\n",
            ")\n",
            "plt.show()\n",
            "print('Saved:', p.name)\n",
        ]),
        md(["## 10. Summary table\n"]),
        code([
            "display(\n",
            "    summary[['case_name','gas','method','pressure_torr',\n",
            "              'final_eta_electron_only','final_eta_net',\n",
            "              'final_keff_over_k0','avg_eta_net','n_steps','status']]\n",
            "    .sort_values(['method','gas','pressure_torr'])\n",
            "    .style.format({\n",
            "        'pressure_torr':           '{:.2e}',\n",
            "        'final_eta_electron_only': '{:.4f}',\n",
            "        'final_eta_net':           '{:.4f}',\n",
            "        'final_keff_over_k0':      '{:.4f}',\n",
            "        'avg_eta_net':             '{:.4f}',\n",
            "    })\n",
            ")\n",
        ]),
    ]
    out = NB_ANALYSIS / "nb_parameter_scan_analysis.ipynb"
    out.write_text(json.dumps(notebook(cells), indent=1, ensure_ascii=False))
    print("Written:", out)


# ── extend __main__ to include new notebooks ─────────────────────────────────

# ── canonical entry point ──────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys as _sys
    scan_only = len(_sys.argv) > 1 and _sys.argv[1] == "--scan-only"

    if not scan_only:
        make_vacuum_nb()
        make_seeded_nb("H2", "1e-5", "0.5", "nb_seeded_h2.ipynb")
        make_seeded_nb("Kr", "1e-6", "0.5", "nb_seeded_kr.ipynb")
        make_callback_nb("H2", "1e-5", "nb_callback_h2.ipynb")
        make_callback_nb("Kr", "1e-6", "nb_callback_kr.ipynb")
        make_analysis_plots_nb()
        make_bb_perveance_nb()
        make_xs_nb()
        make_local_profiles_nb()

    make_parameter_scan_run_nb()
    make_parameter_scan_analysis_nb()
    print("\nAll notebooks written successfully.")
